// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Cja3ZsMMkbgzUR7BqrMNH17ideETCdc',
    appId: '1:608116134696:web:7a51f4813d47adb401b61d',
    messagingSenderId: '608116134696',
    projectId: 'docucare-17528',
    authDomain: 'docucare-17528.firebaseapp.com',
    storageBucket: 'docucare-17528.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb7MUCoMXgqctly23mJit9MWWZp1lZhc8',
    appId: '1:608116134696:android:56acd2f4a61029f601b61d',
    messagingSenderId: '608116134696',
    projectId: 'docucare-17528',
    storageBucket: 'docucare-17528.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAATMFGhKkSNPRj3QeygaZl-xij7gHWK5k',
    appId: '1:608116134696:ios:fd41adbc1f4bb0d401b61d',
    messagingSenderId: '608116134696',
    projectId: 'docucare-17528',
    storageBucket: 'docucare-17528.firebasestorage.app',
    iosBundleId: 'com.example.docdoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAATMFGhKkSNPRj3QeygaZl-xij7gHWK5k',
    appId: '1:608116134696:ios:fd41adbc1f4bb0d401b61d',
    messagingSenderId: '608116134696',
    projectId: 'docucare-17528',
    storageBucket: 'docucare-17528.firebasestorage.app',
    iosBundleId: 'com.example.docdoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7Cja3ZsMMkbgzUR7BqrMNH17ideETCdc',
    appId: '1:608116134696:web:51849c3b48bf7fcb01b61d',
    messagingSenderId: '608116134696',
    projectId: 'docucare-17528',
    authDomain: 'docucare-17528.firebaseapp.com',
    storageBucket: 'docucare-17528.firebasestorage.app',
  );
}
