default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
            app: "1:608116134696:android:4582f93ae8dbae7a01b61d",
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"], 
            android_artifact_type: "APK",
            apk_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
            testers: "softagi.tech@gmail.com",
            release_notes: "Test Lane"
        )
  end
end
